
CREATE TABLE CUSTOMER
(CUSTOMERID VARCHAR2(10) PRIMARY KEY,
CUSTOMERPWD VARCHAR2(15),
CUSTOMERNAME VARCHAR2(15),
CUSTOMEREMAIL VARCHAR2(30),
CUSTOMERTEL VARCHAR2(11),
CUSTOMERZIPCODE VARCHAR2(6),
CUSTOMERADDR1 VARCHAR2(100),
CUSTOMERADDR2 VARCHAR2(100),
CUSTOMERCREATED DATE,
CUSTOMERYEAR VARCHAR2(4),
CUSTOMERMONTH VARCHAR2(2),
CUSTOMERDAY VARCHAR2(2));

CREATE TABLE QNA
(QNANUM NUMBER(6) PRIMARY KEY,
QNATITLE VARCHAR2(50),
QNACONTENT VARCHAR2(300),
CUSTOMERID VARCHAR2(15),
QNACREATED DATE,
QNAANSWER VARCHAR2(5),
QNAHITCOUNT NUMBER(5),
CONSTRAINT CHK_QNA CHECK (QNAANSWER IN('TRUE','FALSE')),
CONSTRAINT QNA_CUSTOMER_ID FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE);

CREATE TABLE ITEM
(ITEMNUM NUMBER(8) PRIMARY KEY,
ITEMNAME VARCHAR2(50),
ITEMCOUNT NUMBER(5),
ITEMPRICE NUMBER(10),
ITEMDISCOUNT NUMBER(10),
ITEMTYPE VARCHAR2(20),
ITEMCONTENT VARCHAR2(50),
ITEMIMAGE1 VARCHAR2(50),
ITEMIMAGE2 VARCHAR2(50),
ITEMIMAGE3 VARCHAR2(50),
ITEMIMAGE4 VARCHAR2(50),
ITEMSTOCK NUMBER(5),
ITEMHITCOUNT NUMBER(5),
CONSTRAINT ITEM_ITEMSTOCK_CK CHECK(ITEMSTOCK>=0));

CREATE TABLE CART
(CARTNUM NUMBER(10) PRIMARY KEY,
CUSTOMERID VARCHAR2(10),
ITEMNUM NUMBER(8),
ITEMPRICE NUMBER(10),
CARTITEMCOUNT NUMBER(10),
CARTTOTPRICE NUMBER(10),
CONSTRAINT CART_ITEM_NUM FOREIGN KEY(ITEMNUM) REFERENCES ITEM(ITEMNUM) ON DELETE CASCADE,
CONSTRAINT CART_CUSTOMER_ID FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE);

CREATE TABLE REVIEW
(CUSTOMERID VARCHAR2(10), 
REVIEWTITLE VARCHAR2(50),
REVIEWCONTENT VARCHAR2(300),
REVIEWNUM NUMBER(10) PRIMARY KEY,
REVIEWCREATED DATE,
REVIEWIMAGE VARCHAR(50),
ITEMNUM NUMBER(8),
REVIEWLIKE NUMBER(5),
CONSTRAINT REVIEW_ITEM_NUM FOREIGN KEY(ITEMNUM) REFERENCES ITEM(ITEMNUM) ON DELETE CASCADE,
CONSTRAINT REVIEW_CUSTOMER_ID FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE);

CREATE TABLE NOTICE
(NOTICENUM NUMBER(5) PRIMARY KEY,
NOTICETITLE VARCHAR2(50),
NOTICECREATED DATE,
NOTICECONTENT VARCHAR2(600),
NOTICEHITCOUNT NUMBER(5),
NOTICEIMAGE VARCHAR2(50),
NOTICESEARCHKEY VARCHAR2(30));

CREATE TABLE REPLY
(REPLYNUM NUMBER(6) PRIMARY KEY,
CUSTOMERID VARCHAR2(10),
REPLYCONTENT VARCHAR2(300),
QNANUM NUMBER(6),
REPLYCREATED DATE,
CONSTRAINT REPLY_QNA_NUM FOREIGN KEY(QNANUM) REFERENCES QNA(QNANUM) ON DELETE CASCADE,
CONSTRAINT REPLY_CUSTOMER_ID FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE);

CREATE TABLE CUSTOMERORDER
(ORDERNUM NUMBER(6) PRIMARY KEY,
CUSTOMERID VARCHAR2(10),
ORDATE DATE,
CUSTOMERORDERNAME VARCHAR2(15),
CUSTOMERORDERZIPCODE VARCHAR2(6),
CUSTOMERORDERADDR1 VARCHAR2(100),
CUSTOMERORDERADDR2 VARCHAR2(100),
CUSTOMERMEMO VARCHAR2(60),
CUSTOMERORDERTEL VARCHAR2(11),
CUSTOMERORDERPAY VARCHAR2(10),
CUSTOMERORDERPRICE NUMBER(20),
CONSTRAINT ORDER_CUSTOMER_ID FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE);

CREATE TABLE CUSTOMERORDERDETAIL
(ORDERNUM NUMBER(6),
CUSTOMERID VARCHAR2(10),
ITEMNUM NUMBER(8),
CARTITEMCOUNT NUMBER(10),
CARTTOTPRICE NUMBER(10),
CONSTRAINT ORDER_DETAIL_NUM FOREIGN KEY(ORDERNUM) REFERENCES CUSTOMERORDER(ORDERNUM) ON DELETE CASCADE,
CONSTRAINT ORDER_DETAIL_ID FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE
);

